### ISSUE TITLE
BUG: In ```CourseService.cs``` DeleteAsync

### ISSUE THREAD

**Issue by MuhammadKasimov** [Zamin-Education/ZaminEducation.Server#153]
```CourseService.cs``` DeleteAsync Should Delete Modules And Attachments
@dastanbayev  please solve it

![image](https://user-images.githubusercontent.com/102380592/195117410-562f60f4-7f6a-469d-9fa5-e84df6ad925a.png)

**Comment by dastanbayev** [comment]
Cascade ini to'g'irlash kk
