### ISSUE TITLE
SERVICE: The `ToPagedList()` Method Is Not Completed ⚠️

### ISSUE THREAD

**Issue by MuhammadUmarqulov** [Zamin-Education/ZaminEducation.Server#45]
https://github.com/Zamin-Education/ZaminEducation.Server/blob/ae4e145cfdee47ce6b70d48152b57d7d649cfcb4/src/ZaminEducation.Service/Extensions/CollectionExtension.cs#L19-L20

**Comment by MrTukhtaboev** [comment]
Done
